// data/portfolio.ts
import type { StockHolding } from './types';

export const portfolioData: StockHolding[] = [
  {
    stockName: 'TCS',
    exchange: 'NSE',
    symbol: 'TCS.NS',
    purchasePrice: 3500,
    quantity: 10,
  },
  {
    stockName: 'INFY',
    exchange: 'NSE',
    symbol: 'INFY.NS',
    purchasePrice: 1400,
    quantity: 20,
  },
  {
    stockName: 'HDFC Bank',
    exchange: 'NSE',
    symbol: 'HDFCBANK.NS',
    purchasePrice: 1500,
    quantity: 15,
  },
  {
    stockName: 'Reliance Industries',
    exchange: 'NSE',
    symbol: 'RELIANCE.NS',
    purchasePrice: 2400,
    quantity: 12,
  },
  {
    stockName: 'ICICI Bank',
    exchange: 'NSE',
    symbol: 'ICICIBANK.NS',
    purchasePrice: 700,
    quantity: 25,
  },
  {
    stockName: 'Larsen & Toubro',
    exchange: 'NSE',
    symbol: 'LT.NS',
    purchasePrice: 2100,
    quantity: 8,
  },
  {
    stockName: 'Maruti Suzuki',
    exchange: 'NSE',
    symbol: 'MARUTI.NS',
    purchasePrice: 8000,
    quantity: 5,
  },
  {
    stockName: 'Bharti Airtel',
    exchange: 'NSE',
    symbol: 'BHARTIARTL.NS',
    purchasePrice: 600,
    quantity: 30,
  },
  {
    stockName: 'Kotak Mahindra Bank',
    exchange: 'NSE',
    symbol: 'KOTAKBANK.NS',
    purchasePrice: 1900,
    quantity: 10,
  },
  {
    stockName: 'Axis Bank',
    exchange: 'NSE',
    symbol: 'AXISBANK.NS',
    purchasePrice: 850,
    quantity: 18,
  },
  {
    stockName: 'Asian Paints',
    exchange: 'NSE',
    symbol: 'ASIANPAINT.NS',
    purchasePrice: 3200,
    quantity: 7,
  },
  {
    stockName: 'Titan Company',
    exchange: 'NSE',
    symbol: 'TITAN.NS',
    purchasePrice: 2500,
    quantity: 9,
  },
  {
    stockName: 'SBI Life Insurance',
    exchange: 'NSE',
    symbol: 'SBILIFE.NS',
    purchasePrice: 1100,
    quantity: 14,
  },
  {
    stockName: 'Bajaj Housing Finance',
    exchange: 'NSE',
    symbol: 'BAJAJHLDNG.NS',
    purchasePrice: 600,
    quantity: 20,
  },
  {
    stockName: 'IDFC Bank',
    exchange: 'NSE',
    symbol: 'IDFCFIRSTB.NS',
    purchasePrice: 55,
    quantity: 100,
  },
  {
    stockName: 'KPIT Technologies',
    exchange: 'NSE',
    symbol: 'KPITTECH.NS',
    purchasePrice: 320,
    quantity: 25,
  },
  {
    stockName: 'LTI Mindtree',
    exchange: 'NSE',
    symbol: 'LTI.NS',
    purchasePrice: 3200,
    quantity: 10,
  },
  {
    stockName: 'Dmart',
    exchange: 'NSE',
    symbol: 'DMART.NS',
    purchasePrice: 2800,
    quantity: 8,
  },
  {
    stockName: 'Tata Consumer Products',
    exchange: 'NSE',
    symbol: 'TATACONSUM.NS',
    purchasePrice: 700,
    quantity: 15,
  },
];
